### ISSUE TITLE
typora1.3.8 不可激活

### ISSUE THREAD

**Issue by lzscxb** [Heriec/typoraCracker#1]
安装你的方法我将 dec_app 复制到Typora目录下的resources，并改名为app

![image](https://user-images.githubusercontent.com/58434904/179338617-9177445a-e1e1-45e9-8d33-78ae6ebaa88e.png)

**Comment by Heriec** [comment]
> 安装你的方法我将 dec_app 复制到Typora目录下的resources，并改名为app
> 
> ![image](https://user-images.githubusercontent.com/58434904/179338617-9177445a-e1e1-45e9-8d33-78ae6ebaa88e.png)

如果你想用现在的新版本的话，这个方法肯定是不行的了，这个只针对原本的老版本用久了过期问题，我放了百度网盘的老版本的Typora了

**Comment by lzscxb** [comment]
嗷 知道了

**Comment by Dragon1573** [comment]
实测 Typora Stable v1.3.8 和 Beta v1.4.1 不可用，我在其他仓库找到了 `typoraCracker` 这个项目。按照 Python 脚本的提示，会发现 `app.asar` 无法被解密（数据没有16位对齐）。
