### ISSUE TITLE
没有找到 1636297098336

### ISSUE THREAD

**Issue by amakerlife** [Heriec/typoraCracker#3]
rt

没有在 `License.js` 文件中找到 `1636297098336`。

Typora version 0.11.18。

并没有使用百度网盘的安装包安装，初步猜测是安装时间不同导致。

请问安装时间，即 `1636297098336` 是什么？如何计算我的安装时间？

**Comment by amakerlife** [comment]
或者说，具体的，问一下这串数字出现在第一行的哪一个位置，即哪一列或哪些列

**Comment by amakerlife** [comment]
经过肉眼观察 及 Ctrl+F 已经找到了那一串数字。

具体的，第一个数字在第 2 行第 1 列左右。

第二至四个数字在第 2 行第 1679 列左右。

**Comment by Heriec** [comment]
> 直接替换就行，一共就4处。而且js文件压缩过，一般都在一行，没必要格式化对齐

**Comment by amakerlife** [comment]
> > 直接替换就行，一共就4处。而且js文件压缩过，一般都在一行，没必要格式化对齐

您可能没有理解我的意思。

我是说

> 没有在 License.js 文件中找到 1636297098336。

即没有找到您在 README 中给出的数字。

目前此问题已经解决，感谢您回复。

**Comment by amakerlife** [comment]
另外，留下解决方法是为了给以后和我相同情况的人提示

**Comment by Heriec** [comment]
> 另外，留下解决方法是为了给以后和我相同情况的人提示

那说一下你的版本可以吗？

**Comment by amakerlife** [comment]
V0.11.18

个人认为不是版本问题，而是安装时间不同的原因
